### ISSUE TITLE
Ctrl+Shift+Z 把 Ctrl + Z 执行了一遍

### ISSUE THREAD

**Issue by Olivia1314** [yuanguandong/react-keyevent#1]
Ctrl + Z = 撤销
Ctrl + Shift + Z = 重做
现在 Ctrl + Shift + Z 同时执行了“撤销” + “重做”

**Comment by yuanguandong** [comment]
> Ctrl + Z = 撤销 Ctrl + Shift + Z = 重做 现在 Ctrl + Shift + Z 同时执行了“撤销” + “重做”

收到，抽空我看看

**Comment by yuanguandong** [comment]
> Ctrl + Z = 撤销 Ctrl + Shift + Z = 重做 现在 Ctrl + Shift + Z 同时执行了“撤销” + “重做”

修复了，试试 react-keyevent@1.1.0
